version: '3'
services:
  postgres:
    image: postgres:alpine3.17
    container_name: hor-postgres
    restart: always
    env_file:
      - ./apps/api/.env
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./.temp/postgresql/data:/var/lib/postgresql/data